'use strict';

// Mapeo de nombres en inglés (API football-data.org) → nombres en español (app)
module.exports = {
  'Czech Republic':           'Chequia',
  'Czechia':                  'Chequia',
  'Mexico':                   'México',
  'South Africa':             'Sudáfrica',
  'South Korea':              'Corea del Sur',
  'Korea Republic':           'Corea del Sur',
  'Bosnia and Herzegovina':   'Bosnia-Herzegovina',
  'Canada':                   'Canadá',
  'Qatar':                    'Catar',
  'Switzerland':              'Suiza',
  'Brazil':                   'Brasil',
  'Haiti':                    'Haití',
  'Morocco':                  'Marruecos',
  'Scotland':                 'Escocia',
  'Australia':                'Australia',
  'Paraguay':                 'Paraguay',
  'Turkey':                   'Turquía',
  'Türkiye':                  'Turquía',
  'USA':                      'USA',
  'United States':            'USA',
  'Curaçao':                  'Curazao',
  'Curacao':                  'Curazao',
  'Ecuador':                  'Ecuador',
  'Germany':                  'Alemania',
  "Côte d'Ivoire":            'Costa de Marfil',
  'Ivory Coast':              'Costa de Marfil',
  'Japan':                    'Japón',
  'Netherlands':              'Países Bajos',
  'Sweden':                   'Suecia',
  'Tunisia':                  'Túnez',
  'Belgium':                  'Bélgica',
  'Egypt':                    'Egipto',
  'Iran':                     'Irán',
  'IR Iran':                  'Irán',
  'New Zealand':              'Nueva Zelanda',
  'Cape Verde':               'Cabo Verde',
  'Saudi Arabia':             'Arabia Saudí',
  'Spain':                    'España',
  'Uruguay':                  'Uruguay',
  'France':                   'Francia',
  'Iraq':                     'Irak',
  'Norway':                   'Noruega',
  'Senegal':                  'Senegal',
  'Algeria':                  'Argelia',
  'Argentina':                'Argentina',
  'Austria':                  'Austria',
  'Jordan':                   'Jordania',
  'Colombia':                 'Colombia',
  'DR Congo':                 'R.D. Congo',
  'Congo DR':                 'R.D. Congo',
  'Democratic Republic of Congo': 'R.D. Congo',
  'Portugal':                 'Portugal',
  'Uzbekistan':               'Uzbekistán',
  'Croatia':                  'Croacia',
  'England':                  'Inglaterra',
  'Ghana':                    'Ghana',
  'Panama':                   'Panamá',
};
